[package]
authors = ["James Chen <jamesc@uniteaudio.com>"]
name = "ch2-app2"
edition = "2024"
version = "0.1.0"


# To run all the tests via `cargo test` the tests need to be explicitly disabled for the binary targets
# If you use a standard main.rs file the following is sufficient:
# [[bin]]
# name = "ch2-app2"
# test = false

[[bin]]
name = "bitfield"
path = "src/bin/bitfield.rs"
test = false

[[bin]]
name = "exception"
path = "src/bin/exception.rs"
test = false

[[bin]]
name = "format"
path = "src/bin/format.rs"
test = false

[[bin]]
name = "hello"
path = "src/bin/hello.rs"
test = false

[[bin]]
name = "levels"
path = "src/bin/levels.rs"
test = false

[[bin]]
name = "micro-arch"
path = "src/bin/micro-arch.rs"
test = false

[[bin]]
name = "overflow"
path = "src/bin/overflow.rs"
test = false

[[bin]]
name = "pac"
path = "src/bin/pac.rs"
test = false

[[bin]]
name = "panic"
path = "src/bin/panic.rs"
test = false

[[bin]]
name = "panic-index"
path = "src/bin/panic-index.rs"
test = false

[[bin]]
name = "semihosting"
path = "src/bin/semihosting.rs"
test = false

[[bin]]
name = "uart"
path = "src/bin/uart.rs"
test = false

[lib]
harness = false

# needed for each integration test
[[test]]
name = "integration"
harness = false

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
semihosting = { version = "0.1.20", features = ["stdio"] }
stm32f3 = { version = "0.16", features = ["stm32f303"] }
# TODO(4) enter your HAL here
# some-hal = "1.2.3"

[dev-dependencies]
defmt-test = "0.3"
